name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zeal-dev-environment/home/extras/zoul0813/zeal-zshell

    steps:
      - name: Setup ZDE
        uses: zoul0813/zeal-dev-environment/github/setup-zde@main
        with:
          deps: zealfs zshell

      - name: Checkout code
        uses: actions/checkout@v6
        with:
            path: zeal-dev-environment/home/extras/zoul0813/zeal-zshell

      - name: Stage coreutils
        run: |
          zde deps stage romdisk coreutils

      - name: Build with ZDE
        run: |
          zde cmake && zde romdisk add bin/zshell

      - name: Create eeprom.img
        run: |
          zde image eeprom add .deploy/eeprom
          zde image eeprom create 64 # custom eeprom image
          cp $ZDE_PATH/mnt/eeprom.img .deploy/eeprom.img

      - name: Build Kernel/Romdisk
        run: |
          zde kernel zoul0813/zeal-zshell/emu
          cp $ZDE_PATH/home/Zeal-8-bit-OS/build/os_with_romdisk.img .deploy/default.img

      - name: Deploy
        uses: ./zeal-dev-environment/home/extras/zoul0813/zeal-zshell/.github/actions/deploy-pages
        with:
            deploy-path: zeal-dev-environment/home/extras/zoul0813/zeal-zshell/.deploy
